package service

import (
	"context"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/statoon54/mailhive/internal/domain"
	"github.com/statoon54/mailhive/internal/test/mocks"
)

func TestTenantService_Create_Success(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	tenant, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Mon Tenant",
	})
	require.NoError(t, err)
	assert.Equal(t, "Mon Tenant", tenant.Name)
	assert.NotEmpty(t, tenant.APIKey)
	assert.True(t, tenant.IsActive)
	assert.Equal(t, "mon-tenant", tenant.Slug)
	assert.Equal(t, domain.MailPriorityDefault, tenant.Settings.DefaultPriority)
}

func TestTenantService_Create_WithSettings(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	tenant, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Custom",
		Settings: &domain.TenantSettings{
			RateLimit:        50,
			RateBurst:        100,
			MaxDestinataires: 200,
			DefaultPriority:  domain.MailPriorityCritical,
		},
	})
	require.NoError(t, err)
	assert.Equal(t, float64(50), tenant.Settings.RateLimit)
	assert.Equal(t, 200, tenant.Settings.MaxDestinataires)
}

func TestTenantService_Create_InvalidSettings(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	_, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Bad",
		Settings: &domain.TenantSettings{
			RateLimit:        0,
			RateBurst:        10,
			MaxDestinataires: 100,
		},
	})
	require.Error(t, err)
	assert.ErrorIs(t, err, domain.ErrValidation)
}

func TestTenantService_Create_SlugAutoGenerated(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	tenant, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Université de Lille",
	})
	require.NoError(t, err)
	assert.Equal(t, "universite-de-lille", tenant.Slug)
}

func TestTenantService_Create_SlugExplicit(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	tenant, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Test",
		Slug: "custom-slug",
	})
	require.NoError(t, err)
	assert.Equal(t, "custom-slug", tenant.Slug)
}

func TestTenantService_Create_RepoError(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	repo.Err = domain.ErrConflict
	svc := NewTenantService(repo)

	_, err := svc.Create(context.Background(), domain.CreateTenantRequest{
		Name: "Test",
	})
	require.Error(t, err)
}

func TestTenantService_GetByID(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)
	id := uuid.New()
	repo.Tenants[id] = &domain.Tenant{ID: id, Name: "Test"}

	tenant, err := svc.GetByID(context.Background(), id)
	require.NoError(t, err)
	assert.Equal(t, "Test", tenant.Name)
}

func TestTenantService_Update_Partial(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)
	id := uuid.New()
	repo.Tenants[id] = &domain.Tenant{
		ID:       id,
		Name:     "Old Name",
		Slug:     "old",
		IsActive: true,
		Settings: domain.TenantSettings{
			RateLimit:        10,
			RateBurst:        10,
			MaxDestinataires: 100,
			DefaultPriority:  domain.MailPriorityDefault,
		},
	}

	newName := "New Name"
	tenant, err := svc.Update(context.Background(), id, domain.UpdateTenantRequest{
		Name: &newName,
	})
	require.NoError(t, err)
	assert.Equal(t, "New Name", tenant.Name)
	assert.Equal(t, "old", tenant.Slug)
}

func TestTenantService_Update_InvalidSettings(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)
	id := uuid.New()
	repo.Tenants[id] = &domain.Tenant{
		ID: id,
		Settings: domain.TenantSettings{
			RateLimit:        10,
			RateBurst:        10,
			MaxDestinataires: 100,
		},
	}

	_, err := svc.Update(context.Background(), id, domain.UpdateTenantRequest{
		Settings: &domain.TenantSettings{
			RateLimit:        0,
			RateBurst:        10,
			MaxDestinataires: 100,
		},
	})
	require.Error(t, err)
	assert.ErrorIs(t, err, domain.ErrValidation)
}

func TestTenantService_List_Pagination(t *testing.T) {
	repo := mocks.NewMockTenantRepo()
	svc := NewTenantService(repo)

	for i := 0; i < 5; i++ {
		id := uuid.New()
		repo.Tenants[id] = &domain.Tenant{ID: id, Name: "T"}
	}

	list, err := svc.List(context.Background(), 1, 20)
	require.NoError(t, err)
	assert.Equal(t, int64(5), list.Total)

	// Test default pagination values
	list, err = svc.List(context.Background(), 0, 0)
	require.NoError(t, err)
	assert.Equal(t, 1, list.Page)
	assert.Equal(t, 20, list.Limit)
}
